In [52]:
import numpy as np

In [8]:
#!pip install numpy

In [9]:
my_list = [10,20,30,40]

In [10]:
type(my_list)

list

In [11]:
np.array(my_list)

array([10, 20, 30, 40])

In [12]:
my_numpy_array = np.array(my_list)

In [13]:
type(my_numpy_array)

numpy.ndarray

In [14]:
my_numpy_array

array([10, 20, 30, 40])

In [15]:
my_numpy_array.max()

np.int64(40)

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.random.random(5) #5 tane 0 ve 1 arasında rastgele sayı oluştur

array([0.94258243, 0.34783798, 0.58313412, 0.91154639, 0.93624827])

In [22]:
#array arithmetic

In [25]:
my_list1 = [1,2]

In [27]:
my_list2 = [2,3]

In [28]:
my_list1 + my_list2

[1, 2, 2, 3]

In [29]:
my_numpy_array1 = np.array(my_list1)

In [30]:
my_numpy_array2 = np.array(my_list2)

In [31]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [32]:
(my_numpy_array1 * my_numpy_array2)

array([2, 6])

In [33]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [34]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [35]:
my_numpy_array1 * 5

array([ 5, 10])

In [36]:
my_list * 5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [49]:
other_array = np.array([10,20,30,40,50])

In [50]:
other_array.min()

np.int64(10)

In [39]:
other_array.max()

np.int64(50)

In [53]:
other_array.sum()

np.int64(150)

In [56]:
#my_numpy_array1 * other_array --> hata verir anca matrislerle

In [57]:
#arange , indexing

In [58]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [59]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [61]:
np_array = np.arange(0,10)

In [62]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np_array[0]

np.int64(0)

In [64]:
np_array[-1]

np.int64(9)

In [65]:
np_array[1:4:]

array([1, 2, 3])

In [66]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [68]:
np_array[2:6:2]

array([2, 4])

In [69]:
#random

In [74]:
np.random.randn(5)

array([-1.95893607,  1.18437412,  0.76431182,  1.87893225,  1.28813896])

In [72]:
np.random.randn(5,5)

array([[-1.07609374, -0.72222246,  0.38850456, -0.55704584, -0.257044  ],
       [ 0.3974089 ,  0.00499816, -0.78499737,  0.94596194,  0.22865584],
       [ 0.88587218, -0.6685976 , -1.73713564,  1.28732848,  1.06203327],
       [ 1.49937984, -0.68207097,  0.51751683, -1.42716969, -0.18795057],
       [ 1.09380442, -0.69009368, -0.47214378, -1.17409424, -0.44196424]])

In [76]:
np.random.randint(1,300,5)

array([145, 178, 103,  46, 216], dtype=int32)