In [1]:
import numpy as np
#https://jalammar.github.io/visual-numpy/

In [2]:
my_matrix = [[5,10],[15,20]]

In [3]:
my_matrix[0]

[5, 10]

In [4]:
my_matrix[0][1]

10

In [5]:
#row * column

In [6]:
numpy_matrix = np.array(my_matrix)

In [7]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [8]:
numpy_matrix[1][0]

np.int64(15)

In [9]:
numpy_matrix.sum()

np.int64(50)

In [10]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.random.random((3,2))

array([[0.86291691, 0.09622194],
       [0.58969624, 0.2911542 ],
       [0.18890806, 0.3972402 ]])

In [13]:
#matrix arithmetic

In [14]:
first_array = np.array([[10,20],[30,40]])

In [15]:
second_array = np.array([[5,15],[25,35]])

In [16]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [19]:
third_array = np.array([[50,60]])

In [20]:
third_array

array([[50, 60]])

In [21]:
first_array + third_array,

(array([[ 60,  80],
        [ 80, 100]]),)

In [22]:
fourth_array = np.array([[5,15,25,35]])

In [24]:
#first_array * fourth_array

In [25]:
first_array * 2

array([[20, 40],
       [60, 80]])

In [26]:
first_array / 2

array([[ 5., 10.],
       [15., 20.]])

In [34]:
# We can add and multiply matrices using arithmetic operators (+-*/) if the two matrices are the same size.

In [28]:
third_array = np.array([[10],[20]])


In [29]:
third_array.shape

(2, 1)

In [30]:
first_array

array([[10, 20],
       [30, 40]])

In [31]:
third_array

array([[10],
       [20]])

In [33]:
first_array + third_array

array([[20, 30],
       [50, 60]])

In [36]:
# We do these arithmetic operations on matrices of different size only if the different dimension is one
#in which case NumPy uses its broadcast rules for that operation:

In [37]:
fourth_array = np.ones((3,4))

In [38]:
fourth_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
# matrix multiplication

In [52]:
first_matrix = np.array([[10,20,30]])

In [53]:
first_matrix

array([[10, 20, 30]])

In [54]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [55]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [56]:
first_matrix.shape

(1, 3)

In [57]:
second_matrix.shape

(3, 2)

In [60]:
#first_matrix * second_matrix

In [59]:
first_matrix.dot(second_matrix)

array([[120, 180]])