In [1]:
import numpy as np

In [3]:
new_array = np.random.randint(1,100,20)

In [4]:
new_array

array([35, 98,  8, 79, 28, 10, 73, 28, 76, 96, 85, 88, 88, 19, 68, 41, 69,
       49, 84, 34], dtype=int32)

In [6]:
new_array > 25

array([ True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True])

In [7]:
new_array[new_array > 25]

array([35, 98, 79, 28, 73, 28, 76, 96, 85, 88, 88, 68, 41, 69, 49, 84, 34],
      dtype=int32)

In [8]:
#transpose & reshape

In [9]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [10]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [12]:
matrix_array.transpose() #rowlar ve columların yeri değişir

array([[10, 20, 30],
       [20, 30, 40]])

In [13]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [14]:
random_array = np.random.random((6,1))

In [15]:
random_array

array([[0.19915595],
       [0.39782548],
       [0.7937114 ],
       [0.47560073],
       [0.12311999],
       [0.07849735]])

In [16]:
random_array.reshape(2,3)

array([[0.19915595, 0.39782548, 0.7937114 ],
       [0.47560073, 0.12311999, 0.07849735]])

In [17]:
random_array.reshape(3,2)

array([[0.19915595, 0.39782548],
       [0.7937114 , 0.47560073],
       [0.12311999, 0.07849735]])

In [18]:
# real life cases

In [19]:
data = np.array([10, 12, 13, 15, 18, 25, 100, 105])

In [20]:
# Compute Z-scores
mean = np.mean(data)

In [21]:
mean

np.float64(37.25)

In [22]:
std = np.std(data)

In [23]:
std

np.float64(37.9333296719389)

In [24]:
z_scores = (data - mean) / std

In [25]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [26]:

np.abs(z_scores) > 1

array([False, False, False, False, False, False,  True,  True])

In [28]:
outliers = data[np.abs(z_scores) > 1]

In [29]:
outliers

array([100, 105])

In [31]:
# math equations

In [32]:
# Solve 2x + 3y = 8 and 5x + 7y = 19

In [33]:
# Coefficients matrix
A = np.array([[2, 3], [5, 7]])

In [34]:
# Constants matrix
b = np.array([8, 19])

In [35]:
# Solve for x and y, linear algebr -> linalg
solution = np.linalg.solve(A, b)

In [36]:
solution

array([1., 2.])

In [37]:
# data analysis

In [39]:
# Stock prices over 5 days
prices = np.array([100, 102, 105, 107, 110])

In [40]:
np.diff(prices)

array([2, 3, 2, 3])

In [42]:
prices[:len(prices)-1:]

array([100, 102, 105, 107])

In [43]:
prices[:-1:]

array([100, 102, 105, 107])

In [44]:
np.diff(prices) / prices[:-1]

array([0.02      , 0.02941176, 0.01904762, 0.02803738])

In [45]:
returns = np.diff(prices) / prices[:-1] * 100